// ============================================================
//  DATA BENDERA
//  Untuk menambah bendera baru, cukup tambah entry di sini.
//  - flag : kode negara 2 huruf (ISO 3166-1 alpha-2)
//           lihat daftar kode: https://flagcdn.com
//  - name : nama negara (dalam Bahasa Indonesia)
//  - region: benua/wilayah untuk filter kategori
// ============================================================

const FLAGS = [
  // ASIA TENGGARA
  { flag: 'id', name: 'Indonesia',       region: 'Asia Tenggara' },
  { flag: 'my', name: 'Malaysia',        region: 'Asia Tenggara' },
  { flag: 'sg', name: 'Singapura',       region: 'Asia Tenggara' },
  { flag: 'th', name: 'Thailand',        region: 'Asia Tenggara' },
  { flag: 'vn', name: 'Vietnam',         region: 'Asia Tenggara' },
  { flag: 'ph', name: 'Filipina',        region: 'Asia Tenggara' },
  { flag: 'mm', name: 'Myanmar',         region: 'Asia Tenggara' },
  { flag: 'kh', name: 'Kamboja',         region: 'Asia Tenggara' },
  { flag: 'la', name: 'Laos',            region: 'Asia Tenggara' },
  { flag: 'tl', name: 'Timor Leste',     region: 'Asia Tenggara' },
  { flag: 'bn', name: 'Brunei',          region: 'Asia Tenggara' },

  // ASIA TIMUR
  { flag: 'jp', name: 'Jepang',          region: 'Asia Timur' },
  { flag: 'kr', name: 'Korea Selatan',   region: 'Asia Timur' },
  { flag: 'kp', name: 'Korea Utara',     region: 'Asia Timur' },
  { flag: 'cn', name: 'China',           region: 'Asia Timur' },
  { flag: 'tw', name: 'Taiwan',          region: 'Asia Timur' },
  { flag: 'mn', name: 'Mongolia',        region: 'Asia Timur' },

  // ASIA SELATAN
  { flag: 'in', name: 'India',           region: 'Asia Selatan' },
  { flag: 'pk', name: 'Pakistan',        region: 'Asia Selatan' },
  { flag: 'bd', name: 'Bangladesh',      region: 'Asia Selatan' },
  { flag: 'np', name: 'Nepal',           region: 'Asia Selatan' },
  { flag: 'lk', name: 'Sri Lanka',       region: 'Asia Selatan' },
  { flag: 'mv', name: 'Maladewa',        region: 'Asia Selatan' },
  { flag: 'bt', name: 'Bhutan',          region: 'Asia Selatan' },

  // ASIA BARAT / TIMUR TENGAH
  { flag: 'sa', name: 'Arab Saudi',      region: 'Timur Tengah' },
  { flag: 'ae', name: 'Uni Emirat Arab', region: 'Timur Tengah' },
  { flag: 'tr', name: 'Turki',           region: 'Timur Tengah' },
  { flag: 'ir', name: 'Iran',            region: 'Timur Tengah' },
  { flag: 'iq', name: 'Irak',                     region: 'Timur Tengah' },
  { flag: 'jo', name: 'Yordania',        region: 'Timur Tengah' },
  { flag: 'lb', name: 'Lebanon',         region: 'Timur Tengah' },
  { flag: 'kw', name: 'Kuwait',          region: 'Timur Tengah' },
  { flag: 'qa', name: 'Qatar',           region: 'Timur Tengah' },
  { flag: 'sy', name: 'Suriah',          region: 'Timur Tengah' },
  { flag: 'ye', name: 'Yaman',           region: 'Timur Tengah' },
  { flag: 'om', name: 'Oman',            region: 'Timur Tengah' },
  { flag: 'bh', name: 'Bahrain',         region: 'Timur Tengah' },

  // EROPA BARAT
  { flag: 'gb', name: 'Inggris',         region: 'Eropa' },
  { flag: 'fr', name: 'Prancis',         region: 'Eropa' },
  { flag: 'de', name: 'Jerman',          region: 'Eropa' },
  { flag: 'it', name: 'Italia',          region: 'Eropa' },
  { flag: 'es', name: 'Spanyol',         region: 'Eropa' },
  { flag: 'pt', name: 'Portugal',        region: 'Eropa' },
  { flag: 'nl', name: 'Belanda',         region: 'Eropa' },
  { flag: 'be', name: 'Belgia',          region: 'Eropa' },
  { flag: 'ch', name: 'Swiss',           region: 'Eropa' },
  { flag: 'at', name: 'Austria',         region: 'Eropa' },
  { flag: 'se', name: 'Swedia',          region: 'Eropa' },
  { flag: 'no', name: 'Norwegia',        region: 'Eropa' },
  { flag: 'dk', name: 'Denmark',         region: 'Eropa' },
  { flag: 'fi', name: 'Finlandia',       region: 'Eropa' },
  { flag: 'pl', name: 'Polandia',        region: 'Eropa' },
  { flag: 'gr', name: 'Yunani',          region: 'Eropa' },
  { flag: 'ie', name: 'Irlandia',        region: 'Eropa' },
  { flag: 'is', name: 'Islandia',        region: 'Eropa' },
  { flag: 'ru', name: 'Rusia',           region: 'Eropa' },
  { flag: 'ua', name: 'Ukraina',         region: 'Eropa' },
  { flag: 'cz', name: 'Ceko',            region: 'Eropa' },
  { flag: 'hu', name: 'Hungaria',        region: 'Eropa' },
  { flag: 'ro', name: 'Rumania',         region: 'Eropa' },
  { flag: 'bg', name: 'Bulgaria',        region: 'Eropa' },
  { flag: 'hr', name: 'Kroasia',         region: 'Eropa' },
  { flag: 'sk', name: 'Slovakia',        region: 'Eropa' },
  { flag: 'si', name: 'Slovenia',        region: 'Eropa' },
  { flag: 'lt', name: 'Lithuania',       region: 'Eropa' },
  { flag: 'lv', name: 'Latvia',          region: 'Eropa' },
  { flag: 'ee', name: 'Estonia',         region: 'Eropa' },
  { flag: 'rs', name: 'Serbia',          region: 'Eropa' },
  { flag: 'ba', name: 'Bosnia',          region: 'Eropa' },
  { flag: 'al', name: 'Albania',         region: 'Eropa' },
  { flag: 'mk', name: 'Makedonia Utara', region: 'Eropa' },

  // AMERIKA
  { flag: 'us', name: 'Amerika Serikat', region: 'Amerika' },
  { flag: 'ca', name: 'Kanada',          region: 'Amerika' },
  { flag: 'mx', name: 'Meksiko',         region: 'Amerika' },
  { flag: 'br', name: 'Brasil',          region: 'Amerika' },
  { flag: 'ar', name: 'Argentina',       region: 'Amerika' },
  { flag: 'cl', name: 'Chile',           region: 'Amerika' },
  { flag: 'co', name: 'Kolombia',        region: 'Amerika' },
  { flag: 've', name: 'Venezuela',       region: 'Amerika' },
  { flag: 'pe', name: 'Peru',            region: 'Amerika' },
  { flag: 'ec', name: 'Ekuador',         region: 'Amerika' },
  { flag: 'bo', name: 'Bolivia',         region: 'Amerika' },
  { flag: 'py', name: 'Paraguay',        region: 'Amerika' },
  { flag: 'uy', name: 'Uruguay',         region: 'Amerika' },
  { flag: 'cu', name: 'Kuba',            region: 'Amerika' },
  { flag: 'jm', name: 'Jamaika',         region: 'Amerika' },
  { flag: 'pa', name: 'Panama',          region: 'Amerika' },
  { flag: 'cr', name: 'Kosta Rika',      region: 'Amerika' },
  { flag: 'gt', name: 'Guatemala',       region: 'Amerika' },

  // AFRIKA
  { flag: 'za', name: 'Afrika Selatan',  region: 'Afrika' },
  { flag: 'eg', name: 'Mesir',           region: 'Afrika' },
  { flag: 'ng', name: 'Nigeria',         region: 'Afrika' },
  { flag: 'ke', name: 'Kenya',           region: 'Afrika' },
  { flag: 'ma', name: 'Maroko',          region: 'Afrika' },
  { flag: 'dz', name: 'Aljazair',        region: 'Afrika' },
  { flag: 'tn', name: 'Tunisia',         region: 'Afrika' },
  { flag: 'ly', name: 'Libya',           region: 'Afrika' },
  { flag: 'sd', name: 'Sudan',           region: 'Afrika' },
  { flag: 'et', name: 'Ethiopia',        region: 'Afrika' },
  { flag: 'gh', name: 'Ghana',           region: 'Afrika' },
  { flag: 'ci', name: 'Pantai Gading',   region: 'Afrika' },
  { flag: 'sn', name: 'Senegal',         region: 'Afrika' },
  { flag: 'cm', name: 'Kamerun',         region: 'Afrika' },
  { flag: 'mz', name: 'Mozambik',        region: 'Afrika' },
  { flag: 'tz', name: 'Tanzania',        region: 'Afrika' },
  { flag: 'ug', name: 'Uganda',          region: 'Afrika' },
  { flag: 'zw', name: 'Zimbabwe',        region: 'Afrika' },
  { flag: 'zm', name: 'Zambia',          region: 'Afrika' },

  // OSEANIA
  { flag: 'au', name: 'Australia',       region: 'Oseania' },
  { flag: 'nz', name: 'Selandia Baru',   region: 'Oseania' },
  { flag: 'pg', name: 'Papua Nugini',    region: 'Oseania' },
  { flag: 'fj', name: 'Fiji',            region: 'Oseania' },
];
